// <auto-generated />
using System;
using Market.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Market.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190104230957_Market")]
    partial class Market
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Market.Models.Categoria", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descricao")
                        .IsRequired();

                    b.HasKey("IdCategoria");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("Market.Models.Endereco", b =>
                {
                    b.Property<int>("IdEndereco")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Bairro")
                        .IsRequired();

                    b.Property<string>("Cep")
                        .IsRequired();

                    b.Property<string>("Cidade")
                        .IsRequired();

                    b.Property<string>("Complemento");

                    b.Property<string>("Numero");

                    b.Property<string>("Rua")
                        .IsRequired();

                    b.HasKey("IdEndereco");

                    b.ToTable("Enderecos");
                });

            modelBuilder.Entity("Market.Models.HistoricoInsumo", b =>
                {
                    b.Property<int>("IdHistoricoInsumo")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DataAdicao");

                    b.Property<string>("Nome")
                        .IsRequired();

                    b.Property<double>("PrecoInsumo");

                    b.Property<double>("Quantidade");

                    b.HasKey("IdHistoricoInsumo");

                    b.ToTable("HistoricoInsumos");
                });

            modelBuilder.Entity("Market.Models.Imagem", b =>
                {
                    b.Property<int>("ImagemId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Caminho");

                    b.Property<DateTime>("DataUpload")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome");

                    b.HasKey("ImagemId");

                    b.ToTable("Imagems");
                });

            modelBuilder.Entity("Market.Models.Insumo", b =>
                {
                    b.Property<int>("IdInsumo")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("EstoqueMax");

                    b.Property<string>("Nome")
                        .IsRequired();

                    b.Property<double>("PrecoInsumo");

                    b.Property<double>("Quantidade");

                    b.HasKey("IdInsumo");

                    b.ToTable("Insumos");
                });

            modelBuilder.Entity("Market.Models.InsumoHasCategoria", b =>
                {
                    b.Property<int>("IdInsumoHasCategoria")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CategoriaId");

                    b.Property<int>("InsumoId");

                    b.HasKey("IdInsumoHasCategoria");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("InsumoId");

                    b.ToTable("InsumoHasCategorias");
                });

            modelBuilder.Entity("Market.Models.Medida", b =>
                {
                    b.Property<int>("IdMedida")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CategoriaId");

                    b.Property<string>("Nome")
                        .IsRequired();

                    b.Property<string>("Sigla")
                        .IsRequired();

                    b.HasKey("IdMedida");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Medidas");
                });

            modelBuilder.Entity("Market.Models.Produto", b =>
                {
                    b.Property<int>("IdProduto")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CategoriaId");

                    b.Property<string>("Descricao")
                        .IsRequired();

                    b.Property<string>("Foto");

                    b.Property<string>("Nome")
                        .IsRequired();

                    b.Property<int?>("TamanhoId");

                    b.Property<double>("Valor");

                    b.HasKey("IdProduto");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("TamanhoId");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("Market.Models.ProdutoHasInsumo", b =>
                {
                    b.Property<int>("IdProdutoHasInsumo")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("InsumoId");

                    b.Property<int>("ProdutoId");

                    b.Property<double>("Quantidade");

                    b.HasKey("IdProdutoHasInsumo");

                    b.HasIndex("InsumoId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("ProdutoHasInsumos");
                });

            modelBuilder.Entity("Market.Models.TipoDeUsuario", b =>
                {
                    b.Property<int>("IdTipoDeUsuario")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descricao")
                        .IsRequired();

                    b.HasKey("IdTipoDeUsuario");

                    b.ToTable("TipoDeUsuarios");
                });

            modelBuilder.Entity("Market.Models.Usuario", b =>
                {
                    b.Property<int>("IdCadastro")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Celular");

                    b.Property<string>("Cpf")
                        .IsRequired();

                    b.Property<DateTime>("DataNascimento");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<int>("EnderecoId");

                    b.Property<string>("Nome")
                        .IsRequired();

                    b.Property<string>("Password");

                    b.Property<string>("Sexo");

                    b.Property<bool>("Status");

                    b.Property<string>("Telefone");

                    b.Property<int>("TipoDeUsuarioId");

                    b.HasKey("IdCadastro");

                    b.HasIndex("EnderecoId");

                    b.HasIndex("TipoDeUsuarioId");

                    b.ToTable("Cadastros");
                });

            modelBuilder.Entity("Market.Models.InsumoHasCategoria", b =>
                {
                    b.HasOne("Market.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Market.Models.Insumo", "Insumo")
                        .WithMany()
                        .HasForeignKey("InsumoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Market.Models.Medida", b =>
                {
                    b.HasOne("Market.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Market.Models.Produto", b =>
                {
                    b.HasOne("Market.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Market.Models.Medida", "Tamanho")
                        .WithMany()
                        .HasForeignKey("TamanhoId");
                });

            modelBuilder.Entity("Market.Models.ProdutoHasInsumo", b =>
                {
                    b.HasOne("Market.Models.Insumo", "Insumo")
                        .WithMany()
                        .HasForeignKey("InsumoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Market.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Market.Models.Usuario", b =>
                {
                    b.HasOne("Market.Models.Endereco", "Endereco")
                        .WithMany()
                        .HasForeignKey("EnderecoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Market.Models.TipoDeUsuario", "TipoDeUsuario")
                        .WithMany()
                        .HasForeignKey("TipoDeUsuarioId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
