-- SELECT * FROM Insumos

-- UPDATE Insumos
-- SET Quantidade = 1000, EstoqueMax = 1000
-- WHERE IdInsumo = 7

-- INSERT INTO EMPREGADOS(CODIGO,NOME, SALARIO, SECAO)
--       SELECT CODIGO,NOME,SALARIO, SECAO
--       FROM EMPREGADOS_FILIAL
--       WHERE DEPARTAMENTO = 2